AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Get next message lambda
Transform:
  - AWS::Serverless-2016-10-31
Parameters:
  MessagesTableArn:
    Type: String
  MessagesTableName:
    Type: String
  Suffix:
    Type: String
Resources:
  GetNextMessageLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub 'GetNextMessageLambdaLayer-${Suffix}'
      CompatibleRuntimes:
        - nodejs12.x
      ContentUri: layer
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs12.x
  GetNextMessageLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'GetNextMessageLambda-${Suffix}'
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: lambda/
      Tracing: Active
      Timeout: 900
      MemorySize: 128
      PackageType: Zip
      Environment:
        Variables:
          MESSAGES_TABLE: !Ref MessagesTableName
      Tags:
        project: backend-chapter-bot
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:*'
              Resource:
                - !Ref MessagesTableArn
                - !Sub '${MessagesTableArn}/index/MessagesBySendTime'
      Layers:
        - !Ref GetNextMessageLambdaLayer
Outputs:
  GetNextMessageLambdaArn:
    Description: Get next message lambda arn
    Value: !GetAtt GetNextMessageLambda.Arn