AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Conversations table
Parameters:
  Suffix:
    Type: String
Resources:
  ConversationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Conversations-${Suffix}'
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: ConversationId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: ConversationId
          AttributeType: S
      Tags:
        - Key: project
          Value: backend-chapter-bot
Outputs:
  ConversationsTableArn:
    Description: Conversations table arn
    Value: !GetAtt ConversationsTable.Arn
  ConversationsTableName:
    Description: Received messages table name
    Value: !Sub 'Conversations-${Suffix}'
