AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Locks table
Parameters:
  Suffix:
    Type: String
Resources:
  LocksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Locks-${Suffix}'
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: LockName
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: LockName
          AttributeType: S
      TimeToLiveSpecification:
        AttributeName: ExpiresAt
        Enabled: true
      Tags:
        - Key: project
          Value: backend-chapter-bot
Outputs:
  LocksTableArn:
    Description: Locks table arn
    Value: !GetAtt LocksTable.Arn
  LocksTableName:
    Description: Received messages table name
    Value: !Sub 'Locks-${Suffix}'
