AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Object storage api
Parameters:
  Bucket:
    Type: String
  Suffix:
    Type: String
Resources:
  ObjectStorageApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource:
                  - !Sub 'arn:aws:s3:::${Bucket}'
                  - !Sub 'arn:aws:s3:::${Bucket}/*'
  ObjectStorageApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'ObjectStorageApiGateway-${Suffix}'
      Description: >-
        Object storage api http proxy
      Tags:
        project: backend-chapter-bot
      StageName: storage
      Auth:
        DefaultAuthorizer: AWS_IAM
      EndpointConfiguration:
        Type: REGIONAL
      TracingEnabled: true
      Variables:
        bucket: !Ref Bucket
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: api-gateway/definition.yaml
Outputs:
  ObjectStorageApiGatewayId:
    Description: Object storage api gateway id
    Value: !Ref ObjectStorageApiGateway
  ObjectStorageApiGatewayEndpoint:
    Description: Object storage api gateway endpoint
    Value: !Sub "${ObjectStorageApiGateway}.execute-api.${AWS::Region}.amazonaws.com"
  ObjectStorageApiGatewayStage:
    Description: Object storage api gateway stage
    Value: storage